[package]
name = "rusty-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "^0.15"
serenity = { version = "^0.11", features = ["client", "standard_framework", "voice", "cache"]}
songbird = { version = "^0.3", features = ["yt-dlp", "builtin-queue", "serenity"]}
tokio = { version = "^1.21", features = ["macros", "rt-multi-thread", "signal"]}
tracing = "^0.1"
tracing-futures = "^0.2"
tracing-subscriber = "^0.3"
