name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: "7.0"
    - name: Test Database Layer
      run: cargo test -p database
    - name: Test Bot
      run: cargo test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Build (Release)
      run: cargo build --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Linux SQLite
        path: ./target/release/rusty_bot
    # - name: Run tests
    #   run: cargo test --verbose
